Nav + first part of background
JaCoWymowny/car-sharing pull request #1
Opened 2021-04-15 19:19 UTC by JaCoWymowny

Nawigacja zrobiona + zacząłem background

2021-04-16 11:20 UTC, kj-ninja reviewed
jest git jak przeczytasz komentarze i zmienisz nazwy klas możesz mergować, następnie pullujesz nowego mastera i odbjiasz sie od nowego mastera z nowym prem.

2021-04-16 11:20 UTC, kj-ninja commented on index.html
> +<header class="banner">
zła nazwa klasy bannerem będzie kolejna sekcja pod headerem nie musisz dawać klasy ponieważ będziesz miał tylko jeden header na stronie

2021-04-16 11:20 UTC, kj-ninja commented on index.html
> +            <img src="images/page-logo.png" alt="">
wiesz czym jest atrybut alt?

2021-04-16 11:20 UTC, kj-ninja commented on index.html
> +            <ul class="list">
sama nazwa klasy list dużo nie mówi zacznij nazywać klasy z sensem np. nav-list

2021-04-16 11:34 UTC, kj-ninja requested changes
dobra jednak coś tam musisz zmienić omówimy temat

2021-04-16 11:34 UTC, kj-ninja commented on css/style.css
> +    background: rgba(0,0,0,0.2);
klasa container powinna miec tylko max-width i ustawienie margina na 0 auto

2021-04-16 11:34 UTC, kj-ninja commented on css/style.css
> +}
ten banner tez musimy omowic i troche zmienic bo teraz banner jest headerem nie moze tak byc

2021-04-16 11:34 UTC, kj-ninja commented on css/style.css
> +    padding: 20px;
czemu padding? mozesz flexem ustawic odstepy i centrowanie

2021-04-16 11:34 UTC, kj-ninja commented on css/style.css
> +}
do wywalenia

2021-04-16 11:34 UTC, kj-ninja commented on css/style.css
> +}
to do przeorania :D

2021-04-17 19:55 UTC, kj-ninja requested changes
popraw alles prawilnie zanim pojdziesz dalej

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +    height: 945px;
nie nadajemny na sztywno wysokosci zmiast tego 100vh zeby na kazdym ekranie zajmowalo 100 wysokosci.

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +    height: 870px;
tutaj to samo 100vh.

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +    justify-content: space-around;
a czemu nie space-between?

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +}
wow co to za czary? to na bank do wywalenia xD nie wiem za bardzo po co to jest?

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +    padding: 20px;
padding logo tez nie jest potrzbeny wystarczy headerowi ustawic height na sztywno i flex zalatwia reszte roboty

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +}
tutaj tak jak mowilem wystarczy zlapac wszystkie a dac im border-right: 1px solid rgba... a nastepnie zlapac a:last-child border: unset;

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +.section-content {
czemu klasa taka dziwna? napisze w htmlu ocb

2021-04-17 19:55 UTC, kj-ninja commented on css/style.css
> +    height: 875px;
znowu height na sztywno nie wiem czemu w sumie

2021-04-17 19:55 UTC, kj-ninja commented on index.html
> +    <div class="section-content container">
po co ten div? mozesz zlapac po prostu section a najlepiej jakbys nadal klade section.banner

2021-04-17 19:55 UTC, kj-ninja commented on index.html
> +    <div class="section-content container">
i dlaczego klasa container? przeciez tutaj nie musisz contentu ograniczac do containera? wystarczy sekcja banner ktora ma 100% width i wyflexowane wszystk ona centrum

2021-04-17 19:55 UTC, kj-ninja commented on index.html
> +        <div class="section-content__button">
tutaj klasa: banner__buttons

2021-04-17 19:55 UTC, kj-ninja commented on index.html
> +            </button>
tu gitara :D

2021-04-18 14:39 UTC, JaCoWymowny commented on css/style.css
> +}
przyciemnienie headera

2021-04-18 15:30 UTC, JaCoWymowny commented on css/style.css
> +    background: rgba(0,0,0,0.2);
zrobione

2021-04-18 17:05 UTC, merged